name: Feedback / Suggestion
description: Drop a feedback or suggestion
title: '[Feedback] '
labels: ['🈸 Feature Request']
body:
  - type: textarea
    attributes:
      label: Feedback / Suggestion
      description: Write your feedback or suggestion and leave them here.
      render: markdown
    validations:
      required: true
